stages:
  - test
  - release


.python_test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y ffmpeg
    - python runtests.py

head:
  extends: .python_test
  image: python:3.8
  before_script:
    - pip install .['testing']

lts_27:
  extends: .python_test
  image: python:3.7
  extends: .python_test
  before_script:
    - pip install .['testing'] wagtail~=2.7 django~=2.2

lts_211:
  image: python:3.8
  extends: .python_test
  before_script:
    - pip install .['testing'] wagtail~=2.11 django~=3.1

build:
    image: python:3.8
    stage: release
    before_script:
        - pip install --upgrade setuptools wheel twine
    script:
        - ./setup.py sdist bdist_wheel
        - twine upload dist/*
    only:
        - tags
