language: python
dist: xenial


cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv

env:
  global:
    - DJANGO_SETTINGS_MODULE="tests.app.settings"

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
    - sudo add-apt-repository ppa:mc3man/xerus-media -y
    - sudo apt-get update -qq
    # The install of ffmpeg fails at random with 'There were unauthenticated packages' 🤷‍♂️
    - sudo apt-get install ffmpeg --allow-unauthenticated -y

install:
  - pip install --upgrade pip wheel tox-travis


script:
  - tox
